### ISSUE TITLE
[v1.0.0] Error whoile try to start the pod: `AccessControlException: access denied`

### ISSUE THREAD

**Issue by blavenie** [duniter-gchange/gchange-pod#3]
```bash
[2019-01-02 19:49:32,753][INFO ][node                     ] [Ernst] version[2.4.6], pid[26900], build[5376dca/2017-07-18T12:17:44Z]
[2019-01-02 19:49:32,753][INFO ][node                     ] [Ernst] initializing ...
[2019-01-02 19:49:33,425][INFO ][plugins                  ] [Ernst] modules [reindex, lang-expression, lang-groovy], plugins [mapper-attachments, cesium-plus-pod-core, cesium-plus-pod-subscription, cesium-plus-pod-user, gchange], sites []
[2019-01-02 19:49:33,478][INFO ][env                      ] [Ernst] using [1] data paths, mounts [[/home (/dev/sda3)]], net usable_space [1.6tb], net total_space [1.7tb], spins? [possibly], types [ext4]
[2019-01-02 19:49:33,478][INFO ][env                      ] [Ernst] heap size [989.8mb], compressed ordinary object pointers [true]
Exception in thread "main" java.lang.ExceptionInInitializerError
Likely root cause: java.security.AccessControlException: access denied ("java.io.FilePermission" "/etc/ld.so.conf" "read")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
        at java.io.File.exists(File.java:814)
        at jnr.ffi.LibraryLoader$StaticDataHolder.<clinit>(LibraryLoader.java:421)
        at jnr.ffi.LibraryLoader.getSearchPaths(LibraryLoader.java:353)
        at jnr.ffi.LibraryLoader.load(LibraryLoader.java:325)
        at jnr.ffi.LibraryLoader.load(LibraryLoader.java:304)
        at org.abstractj.kalium.NaCl$SingletonHolder.<clinit>(NaCl.java:51)
        at org.abstractj.kalium.NaCl.sodium(NaCl.java:29)
        at org.duniter.core.service.Ed25519CryptoServiceImpl.<init>(Ed25519CryptoServiceImpl.java:73)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.duniter.core.beans.BeanFactory.newBean(BeanFactory.java:121)
        at org.duniter.elasticsearch.beans.ESBeanFactory.newBean(ESBeanFactory.java:54)
        at org.duniter.core.beans.BeanFactory.getBean(BeanFactory.java:60)
        at org.duniter.elasticsearch.service.ServiceLocator$Provider.get(ServiceLocator.java:123)
        at org.duniter.elasticsearch.service.ServiceLocator$Provider.get(ServiceLocator.java:114)
        at <<<guice>>>
        at org.elasticsearch.node.Node.<init>(Node.java:213)
```

**Comment by blavenie** [comment]
Was due to and invalid config file, without security manager disable
